name: pipeline when there is a merge test

on:
  pull_request:
    branches:
      - main  #there is merge from test branch to main branch
    types:
      - closed

permissions:
  contents: read

jobs:
  build-jobA:
    runs-on: ubuntu-latest/docker/.k8s/windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        uses: python3.0
        uses: java12

      

      - name: Run Job A
        run: |
          echo "run jobA on push"
          apt install
          make windclient

  merge-jobB:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Job B
        run: |
          echo "run jobB on push"