# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: pipeline when there is a merge

on:
  pull_request:
    branches:
      - main  //there is merge from test branch to main branch
    types:
      - closed

permissions:
  contents: read

  jobB:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Job B
        run: |
          echo "run jobB when merging from testBranch to main"
