name: pipeline when there is a merge

on:
  pull_request:
    branches:
      - main  #there is merge from test branch to main branch
    types:
      - closed

permissions:
  contents: read

jobs:
  merge-jobA:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Job A
        run: |
          echo "run jobA on push"

  merge-jobB:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Job B
        run: |
          echo "run jobB on push"