name: pipeline when there is a push on test-branchA

on:
  push:
    branches: [ "test-branchA" ]

permissions:
  contents: read

jobs:
  push-jobA:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Job A
        run: |
          echo "run jobA on push"

  push-jobB:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Job B
        run: |
          cat ./.github/workflows/test-dependency-pipeline.yml
          echo "run jobB on push"

  push-jobC:
    uses: ./.github/workflows/test-dependency-pipeline.yml@1.0
    with:
      username: Guillaume

    