# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch: //test

permissions:
  contents: read

jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Job A
        run: |
          echo "run jobA on push"

  jobB:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Job B
        run: |
          echo "run jobB when merging from testBranch to main"

  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Set up Python 3.10
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: "3.10"
  #   - name: Test stage
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install flake8 pytest
  #       python test.py
