name: test dependency1

on:
  workflow_call:
    inputs:
        config-path:
          required: true
          type: string

permissions:
  contents: read

jobs:
  dependent-job:
    runs-on: ubuntu-latest

    steps:
    - name: Print parameters
      run: |
        echo "Parameter 1: ${{ inputs.config-path }}"