name: test dependency1

on:
  workflow_call:
    outputs:
        firstword:
          description: "The first output string"
          value: ${{ jobs.example_job.outputs.output1 }}
        secondword:
          description: "The second output string"
          value: ${{ jobs.example_job.outputs.output2 }}

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      output2: ${{ steps.step2.outputs.secondword }}
    steps:
      - id: step1
        run: echo "firstword=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "secondword=world" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: example_job
    steps:
      - env:
          OUTPUT1: ${{needs.example_job.outputs.output1}}
          OUTPUT2: ${{needs.example_job.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"