name: test dependency1

on:
  workflow_call:

permissions:
  contents: read

jobs:
  dependent-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v4
      with:
        configuration-path: ${{ inputs.config-path }}
      name: Print parameters
      run: |
        echo "Parameter 1: ${{ inputs.config-path }}"