name: test dependency1

on:
  workflow_call:

permissions:
  contents: read

jobs:
  dependent-job:
    runs-on: ubuntu-latest

    steps:
    - name: Print parameters
      run: |
        echo "Parameter 1: ${{ github.event.inputs.parameter1 }}"
        echo "Parameter 2: ${{ github.event.inputs.parameter2 }}"