name: test dependency

on:
  workflow_run:
    workflows: ["pipeline when there is a push on test-branchA"]
    types:
      - completed
  workflow_call:

permissions:
  contents: read

jobs:
  dependent-job:
    runs-on: ubuntu-latest

    steps:
    - name: Print parameters
      run: |
        echo "Parameter 1: ${{ github.event.inputs.parameter1 }}"
        echo "Parameter 2: ${{ github.event.inputs.parameter2 }}"