name: test dependency1

on:
  workflow_call:
    inputs:
        # config-path:
        #   required: true
        #   type: string
        value1:

permissions:
  contents: read

jobs:
  dependent-job:
    runs-on: ubuntu-latest
    uses: actions/labeler@v4

    steps:
    - name: Print parameters
      run: |
        echo "Parameter 1: ${{ inputs.value1 }}"